name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quanta-blotter-hyper
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "21"

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - name: Lint
        run: clojure -M:lint

      - name: Lint demo
        working-directory: demo
        run: clojure -M:lint

      - name: Run unit tests
        run: clojure -M:test

      - name: Build jar
        run: clojure -T:build jar

      - name: Publish to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -T:build deploy
